const ClipArt = [
  {
    groupeTitle: "espace",
    url: [
      "http://localhost:5000/clipart/Astro_1_qnbtkj.png",
      "http://localhost:5000/clipart/Astro_3_ignkzk.png",
      "http://localhost:5000/clipart/Astro_4_gub10q.png",
      "http://localhost:5000/clipart/Astro_6_nlfyyb.png",
      "http://localhost:5000/clipart/Astro_2_waxmjt.png",
      "http://localhost:5000/clipart/Astro_7_gtqoem.png",
      "http://localhost:5000/clipart/Astro_5_wo3n2o.png",
      "http://localhost:5000/clipart/Astro10_krhvdt.png",
      "http://localhost:5000/clipart/Astro_8_z4xn6s.png",
      "http://localhost:5000/clipart/Astro9_kwcthp.png",
      "http://localhost:5000/clipart/space10_ogw8rw.png",
      "http://localhost:5000/clipart/space11_xoehgq.png",
      "http://localhost:5000/clipart/space12_bxc7bm.png",
      "http://localhost:5000/clipart/space13_orzpi4.png",
      "http://localhost:5000/clipart/space14_gmqdlw.png",
      "http://localhost:5000/clipart/space15_nckrht.png",
      "http://localhost:5000/clipart/space16_kxdaal.png",
      "http://localhost:5000/clipart/space18_xakjof.png",
      "http://localhost:5000/clipart/space19_ggwfi5.png",
      "http://localhost:5000/clipart/space1_yedmvw.png",
      "http://localhost:5000/clipart/space20_hviaej.png",
      "http://localhost:5000/clipart/space21_nhxbto.png",
      "http://localhost:5000/clipart/space22_uedpw9.png",
      "http://localhost:5000/clipart/space23_nwrr04.png",
      "http://localhost:5000/clipart/space24_dw0cqg.png",
      "http://localhost:5000/clipart/space25_edsm9i.png",
      "http://localhost:5000/clipart/space26_qlsn0b.png",
      "http://localhost:5000/clipart/space27_omhoxs.png",
      "http://localhost:5000/clipart/space28_opaqgk.png",
      "http://localhost:5000/clipart/space29_zgrl70.png",
      "http://localhost:5000/clipart/space2_sxdrbh.png",
      "http://localhost:5000/clipart/space30_tjikru.png",
      "http://localhost:5000/clipart/space31_rxgvmu.png",
      "http://localhost:5000/clipart/space32_lvrzsl.png",
      "http://localhost:5000/clipart/space3_pdwc6p.png",
      "http://localhost:5000/clipart/space4_jxkutt.png",
      "http://localhost:5000/clipart/space5_nxe3z1.png",
      "http://localhost:5000/clipart/space6_skculy.png",
      "http://localhost:5000/clipart/space7_y3xzqz.png",
      "http://localhost:5000/clipart/space8_n4rm5t.png",
      "http://localhost:5000/clipart/space9_yg9ip0.png",
    ],
  },
  {
    groupeTitle: "nourriture",
    url: [
      "http://localhost:5000/clipart/sandwitch_uvjxxk.png",
      "http://localhost:5000/clipart/sandwitch2_yyfd05.png",
      "http://localhost:5000/clipart/pizza2_tn2uox.png",
      "http://localhost:5000/clipart/pizza1_smfmtd.png",
      "http://localhost:5000/clipart/pizza0_nzaijd.png",
      "http://localhost:5000/clipart/orange_v84vtl.png",
      "http://localhost:5000/clipart/mongue_lyig6f.png",
      "http://localhost:5000/clipart/kiwi_cndftb.png",
      "http://localhost:5000/clipart/hotdog_amzv8r.png",
      "http://localhost:5000/clipart/honey1_rb5uji.png",
      "http://localhost:5000/clipart/glace_ylz8ro.png",
      "http://localhost:5000/clipart/fruit_oqd23y.png",
      "http://localhost:5000/clipart/fries_v4i7a7.png",
      "http://localhost:5000/clipart/fraise_mbtotx.png",
      "http://localhost:5000/clipart/figue_vruwef.png",
      "http://localhost:5000/clipart/fajitas_mdevo9.png",
      "http://localhost:5000/clipart/donuts2_atzdvk.png",
      "http://localhost:5000/clipart/donuts1_nnj542.png",
      "http://localhost:5000/clipart/citron2_ane9w3.png",
      "http://localhost:5000/clipart/citron1_etnlzn.png",
      "http://localhost:5000/clipart/burger3_mfdpvc.png",
      "http://localhost:5000/clipart/burger2_bw1ntp.png",
      "http://localhost:5000/clipart/banane_d2v4n4.png",
      "http://localhost:5000/clipart/avocat_uqba5b.png",
      "http://localhost:5000/clipart/ananas_hdci1m.png",
    ],
  },
  {
    groupeTitle: "animeaux",
    url: [
      "http://localhost:5000/clipart/Bird1_r2qtnn.png",
      "http://localhost:5000/clipart/Bird2_csjpt9.png",
      "http://localhost:5000/clipart/Bird3_xbbpyt.png",
      "http://localhost:5000/clipart/bear_yyrrus.png",
      "http://localhost:5000/clipart/dog1_uiegim.png",
      "http://localhost:5000/clipart/dog2_r7yugy.png",
      "http://localhost:5000/clipart/dog3_h763q3.png",
      "http://localhost:5000/clipart/gangsta2_nc6sfn.png",
      "http://localhost:5000/clipart/gorilla_ee7hri.png",
      "http://localhost:5000/clipart/lion2_jtaddj.png",
      "http://localhost:5000/clipart/lion3_ohdqzo.png",
      "http://localhost:5000/clipart/lion4_fmpw4p.png",
      "http://localhost:5000/clipart/lion_isfdaa.png",
      "http://localhost:5000/clipart/monkey2_glosrj.png",
      "http://localhost:5000/clipart/monkey_v1op9f.png",
      "http://localhost:5000/clipart/nft_hkwykw.png",
    ],
  },
  {
    groupeTitle: "statue",
    url: [
      "http://localhost:5000/clipart/status2_jcegkt.png",
      "http://localhost:5000/clipart/status3_krjmqi.png",
      "http://localhost:5000/clipart/status4_ms8dy8.png",
      "http://localhost:5000/clipart/status5_bvirn7.png",
      "http://localhost:5000/clipart/status6_pzpzkl.png",
      "http://localhost:5000/clipart/status7_xyk3hs.png",
      "http://localhost:5000/clipart/status8_wxoblh.png",
      "http://localhost:5000/clipart/status9_jyzgss.png",
      "http://localhost:5000/clipart/status_nkjlgq.png",
      "http://localhost:5000/clipart/status10_m8qijy.png",
      "http://localhost:5000/clipart/status14_jzbnbq.png",
      "http://localhost:5000/clipart/status13_kcp4aw.png",
      "http://localhost:5000/clipart/status15_u176ro.png",
      "http://localhost:5000/clipart/status12_q3kylh.png",
      "http://localhost:5000/clipart/status11_oka0cb.png",
    ],
  },
  {
    groupeTitle: "plume",
    url: [
      "http://localhost:5000/clipart/wings1_c6fmud.png",
      "http://localhost:5000/clipart/wings2_zkylrm.png",
      "http://localhost:5000/clipart/wings3_qrn18g.png",
      "http://localhost:5000/clipart/wings5_hf1lou.png",
      "http://localhost:5000/clipart/wings6_wq32dl.png",
      "http://localhost:5000/clipart/wings7_jn26eg.png",
      "http://localhost:5000/clipart/wings8_ztz3qx.png",
    ],
  },
  {
    groupeTitle: "amoure",
    url: [
      "http://localhost:5000/clipart/love_naq1wv.png",
      "http://localhost:5000/clipart/love9_ffj04z.png",
      "http://localhost:5000/clipart/love8_otkl8x.png",
      "http://localhost:5000/clipart/love7_wkx6g5.png",
      "http://localhost:5000/clipart/love6_cmhcmo.png",
      "http://localhost:5000/clipart/love5_cipw6d.png",
      "http://localhost:5000/clipart/love4_jewyad.png",
      "http://localhost:5000/clipart/love3_s4hth0.png",
      "http://localhost:5000/clipart/love2_bb8zis.png",
      "http://localhost:5000/clipart/love13_g7oknz.png",
      "http://localhost:5000/clipart/love12_ar8aru.png",
      "http://localhost:5000/clipart/love11_ewuekv.png",
      "http://localhost:5000/clipart/love10_ht5dby.png",
      "http://localhost:5000/clipart/lips_qwbxxr.png",
    ],
  },
  {
    groupeTitle: "café",
    url: [
      "http://localhost:5000/clipart/coffee_wydqa6.png",
      "http://localhost:5000/clipart/coffee5_fm0ddn.png",
      "http://localhost:5000/clipart/coffee4_milhms.png",
      "http://localhost:5000/clipart/coffee3_bsay0z.png",
      "http://localhost:5000/clipart/coffee2_b8qkjm.png",
      "http://localhost:5000/clipart/coffee9_jcwds9.png",
      "http://localhost:5000/clipart/coffee11_ubqazc.png",
      "http://localhost:5000/clipart/coffee8_mj52uy.png",
      "http://localhost:5000/clipart/coffee12_tcb2qx.png",
      "http://localhost:5000/clipart/coffee13_ravvoe.png",
      "http://localhost:5000/clipart/coffee14_odsc28.png",
      "http://localhost:5000/clipart/coffee10_xnmwih.png",
    ],
  },
  {
    groupeTitle: "psychedelic",
    url: [
      "http://localhost:5000/clipart/alien11_rymymi.png",
      "http://localhost:5000/clipart/alien12_ivim8w.png",
      "http://localhost:5000/clipart/alien2_aslvmr.png",
      "http://localhost:5000/clipart/alien16_jnwihf.png",
      "http://localhost:5000/clipart/alien1_mqepvi.png",
      "http://localhost:5000/clipart/alien3_qfb8zr.png",
      "http://localhost:5000/clipart/alien4_ix5ei6.png",
      "http://localhost:5000/clipart/alien14_vgnah9.png",
      "http://localhost:5000/clipart/alien7_msbkdv.png",
      "http://localhost:5000/clipart/alien5_sqhz0e.png",
      "http://localhost:5000/clipart/alien10_xh3vzy.png",
      "http://localhost:5000/clipart/alien8_y0yim7.png",
      "http://localhost:5000/clipart/alien9_kgjmx6.png",
      "http://localhost:5000/clipart/alien6_fo90zy.png",
      "http://localhost:5000/clipart/psychedelic10_yhpglj.png",
      "http://localhost:5000/clipart/psychedelic1_tgmuji.png",
      "http://localhost:5000/clipart/psychedelic2_xjeqr1.png",
      "http://localhost:5000/clipart/psychedelic3_kulffb.png",
      "http://localhost:5000/clipart/psychedelic4_bhyx0y.png",
      "http://localhost:5000/clipart/psychedelic5_asblsa.png",
      "http://localhost:5000/clipart/psychedelic6_dlnfst.png",
      "http://localhost:5000/clipart/psychedelic7_xcjqkh.png",
      "http://localhost:5000/clipart/psychedelic8_bhkoek.png",
      "http://localhost:5000/clipart/psychedelic9_mqv0ve.png",
    ],
  },
  {
    groupeTitle: "monuments",
    url: [
      "http://localhost:5000/clipart/monument9_q5rdom.png",
      "http://localhost:5000/clipart/monument8_uwvyra.png",
      "http://localhost:5000/clipart/monument7_wfxins.png",
      "http://localhost:5000/clipart/monument6_erhhgh.png",
      "http://localhost:5000/clipart/monument5_oodl1f.png",
      "http://localhost:5000/clipart/monument4_p4bs6l.png",
      "http://localhost:5000/clipart/monument3_dmaqti.png",
      "http://localhost:5000/clipart/monument2_cvgvh5.png",
      "http://localhost:5000/clipart/monument1_wmz3hx.png",
      "http://localhost:5000/clipart/monument16_ikc3ng.png",
      "http://localhost:5000/clipart/monument15_llgvuj.png",
      "http://localhost:5000/clipart/monument14_b17c9k.png",
      "http://localhost:5000/clipart/monument13_av0uty.png",
      "http://localhost:5000/clipart/monument12_iykzbe.png",
      "http://localhost:5000/clipart/monument11_u5m5wa.png",
      "http://localhost:5000/clipart/monument10_jvcq80.png",
    ],
  },
  {
    groupeTitle: "fleurs",
    url: [
      "http://localhost:5000/clipart/flower_hrijby.png",
      "http://localhost:5000/clipart/flowers2_gml6km.png",
      "http://localhost:5000/clipart/flowers3_g6dekk.png",
      "http://localhost:5000/clipart/flowers_krkgdw.png",
      "http://localhost:5000/clipart/frame10_n1tqux.png",
      "http://localhost:5000/clipart/frame11_fbhize.png",
      "http://localhost:5000/clipart/frame12_l125kc.png",
      "http://localhost:5000/clipart/frame13_pzchwr.png",
    ],
  },
  {
    groupeTitle: "cadre",
    url: [
      "http://localhost:5000/clipart/frame14_jcgycl.png",
      "http://localhost:5000/clipart/frame15_agkze8.png",
      "http://localhost:5000/clipart/frame1_xm81z1.png",
      "http://localhost:5000/clipart/frame2_avmwiv.png",
      "http://localhost:5000/clipart/frame3_aakqht.png",
      "http://localhost:5000/clipart/frame4_srh1qu.png",
      "http://localhost:5000/clipart/frame5_xagkue.png",
      "http://localhost:5000/clipart/frame6_pzbost.png",
      "http://localhost:5000/clipart/frame7_gvn0jn.png",
      "http://localhost:5000/clipart/frame8_ph6xqg.png",
      "http://localhost:5000/clipart/frame9_jnhr2r.png",
    ],
  },
  {
    groupeTitle: "lunettes",
    url: [
      "http://localhost:5000/clipart/lunette1_z1cnxm.png",
      "http://localhost:5000/clipart/lunette2_ykdlfk.png",
      "http://localhost:5000/clipart/lunette3_rr3b4c.png",
      "http://localhost:5000/clipart/lunette4_t75ipw.png",
      "http://localhost:5000/clipart/lunette5_obovug.png",
      "http://localhost:5000/clipart/lunette6_dcykap.png",
      "http://localhost:5000/clipart/lunette7_kx6dep.png",
      "http://localhost:5000/clipart/lunette8_gz4rk2.png",
      "http://localhost:5000/clipart/lunette9_eeqmeb.png",
    ],
  },
  {
    groupeTitle: "manettes",
    url: [
      "http://localhost:5000/clipart/manette9_cjq7gt.png",
      "http://localhost:5000/clipart/manette8_y0j1qr.png",
      "http://localhost:5000/clipart/manette7_ta9f2p.png",
      "http://localhost:5000/clipart/manette6_eakkct.png",
      "http://localhost:5000/clipart/manette5_f9iz1t.png",
      "http://localhost:5000/clipart/manette4_trq4zw.png",
      "http://localhost:5000/clipart/manette3_hugyqj.png",
      "http://localhost:5000/clipart/manette2_jdank9.png",
      "http://localhost:5000/clipart/manette1_mv46r4.png",
      "http://localhost:5000/clipart/manette12_ssiamd.png",
      "http://localhost:5000/clipart/manette11_gwiazp.png",
      "http://localhost:5000/clipart/manette10_dkxp3r.png",
    ],
  },
  {
    groupeTitle: "autres...",
    url: [
      "http://localhost:5000/clipart/zombie1_vavu0j.png",
      "http://localhost:5000/clipart/nature_bsnjs0.jpg",
      "http://localhost:5000/clipart/lum_q1c6ol.png",
      "http://localhost:5000/clipart/lum2_dzuxbh.png",
      "http://localhost:5000/clipart/gangsta_ue1qx3.png",
      "http://localhost:5000/clipart/gangsta1_kotlga.png",
      "http://localhost:5000/clipart/crown_hpjv42.png",
    ],
  },
  {
    groupeTitle: "guitars",
    url: [
      "http://localhost:5000/clipart/guitar_2_srqlsh.png",
      "http://localhost:5000/clipart/guitar4_kwpxiy.png",
      "http://localhost:5000/clipart/guitar3_srcyie.png",
      "http://localhost:5000/clipart/guitar1_jksdw7.png",
      "http://localhost:5000/clipart/guitar5_ikdu6t.png",
    ],
  },
  {
    groupeTitle: "egypte",
    url: [
      "http://localhost:5000/clipart/egypt8_eqbvpg.png",
      "http://localhost:5000/clipart/egypt7_jim8dr.png",
      "http://localhost:5000/clipart/egypt6_hpmok1.png",
      "http://localhost:5000/clipart/egypt5_vyntd4.png",
      "http://localhost:5000/clipart/egypt4_mmmt7c.png",
      "http://localhost:5000/clipart/egypt3_vvd9ht.png",
      "http://localhost:5000/clipart/egypt2_q69mr2.png",
      "http://localhost:5000/clipart/egypt1_lxigkz.png",
    ],
  },
]
export default ClipArt
