/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Alben Tan (https://sketchfab.com/albentan2012)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/sleeping-cat-on-the-bed-1-3d-scan-ae07a741be6944e8ba5e2657069d3aaf
title: Sleeping Cat On The Bed 1 - 3D scan
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"

export default function ModelDraco({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF("/modelDraco.gltf")
  return (
    <group scale={10} ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[-0.01, 0, -0.02]}
            rotation={[-Math.PI, 1.56, -Math.PI]}
          >
            <mesh
              geometry={nodes.Object_4.geometry}
              material={materials["Material_0.006"]}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload("/modelDraco.gltf")
